type: topic
label: Account Information Summary
base_view: account
model_name: peoplepulse_model
description: The kl;kl;kl;k hello im testing and its actually worse
zoe_description: The Account Information Summary view provides detailed metrics and
  attributes for accounts, including contact details, location, industry classification,
  and size. It indicates churn status and includes renewal and contract start dates.
  Utilize account size averages and churned versus total account numbers for performance
  and retention assessments.
hidden: false
views: {}
