base_view: candy_shop_orders
name: candy_shop_orders
model_name: zenlytic_managed
label: Candy Shop
description: ''
views:
  candy_shop_order_items:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${candy_shop_orders.order_id}=${candy_shop_order_items.order_id}
type: topic
