base_view: candy_shop_suppliers
model_name: zenlytic_managed
label: Candy Shop
description: ''
views:
  candy_shop_customers:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${candy_shop_suppliers.supplier_id}=${candy_shop_customers.customer_id}
  candy_shop_order_items:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: >-
        ${candy_shop_suppliers.supplier_id}=${candy_shop_order_items.order_item_id}
  candy_shop_orders:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${candy_shop_suppliers.supplier_id}=${candy_shop_orders.order_id}
type: topic
