# type: topic 
label: Marketing Spend Analysis
base_view: marketing_spend
model_name: peoplepulse_model
description: The 'Marketing Spend Analysis' view captures key metrics related to marketing
  campaigns and expenditures. It includes fields such as engagement, source, spend
  amount, channel, and reach of marketing efforts. The data covers individual campaigns
  and aggregated metrics like total engagement, total spend, total reach, the number
  of campaigns, and spend-to-reach ratio. This view helps in assessing the efficiency
  and effectiveness of different marketing strategies.
zoe_description: The 'Marketing Spend Analysis' view provides insights into marketing
  campaign performance, focusing on metrics like engagement levels, expenditure, channels,
  and reach. It includes both granular and aggregate data, facilitating a comprehensive
  evaluation of marketing strategies and their outcomes. Use this to optimize future
  marketing investments and improve ROI.
hidden: false
views: {}
