type: topic
base_view: product
model_name: peoplepulse_model
label: Product Information
description: >-
  The 'Product Information' view provides details about individual products. It
  includes a unique identifier for each product (PRODUCT_ID), the type of
  product (PRODUCT_TYPE), and the product's name (PRODUCT_NAME). This view is
  essential for cataloging products, managing inventory, and facilitating
  user-friendly product searches. Accurate and structured data within this view
  supports effective product management and customer interactions.
zoe_description: >-
  The 'Product Information' view contains fields for PRODUCT_ID (unique
  identifier), PRODUCT_TYPE (category), and PRODUCT_NAME (name). When
  interacting, reference these fields to identify, categorize, or search for
  specific products.
hidden: false
views: {}
